#!/usr/bin/env ruby

require 'csv'
require 'json'
require 'thread/pool'

class TransformDctr
  THREAD_COUNT = 25

  attr_accessor :in, :out

  def initialize(_in, _out)
    @in, @out = _in, _out
  end

  def transform
    self.in.each_line do |line|
      pool.process { process_line(line) }
    end

    close
  end

  private
  def pool
    @pool ||= Thread.pool(THREAD_COUNT)
  end

  def process_line(line)
    dctr = Dctr.new(line)
    self.out << "#{dctr.meta}\n#{dctr.json}\n"
  end

  def close
    pool.shutdown
  end
end

class Dctr
  attr_accessor :csv

  def self.meta
    @meta ||= { action: :update }.to_json
  end

  def initialize(line)
    CSV.parse(line) do |row|
      @csv = row
    end
  end

  def meta
    self.class.meta
  end

  def json
    @json ||= { npi: @csv[0] }.to_json
  end
end

TransformDctr.new(ARGF, $stdout).transform
