// Generated by CoffeeScript 1.7.1
(function() {
  var Dctr;

  Dctr = (function() {
    function Dctr(csv) {
      this.csv = csv;
    }

    Dctr.prototype.meta = function() {
      return JSON.stringify(this.metaAttrs());
    };

    Dctr.prototype.json = function() {
      return JSON.stringify(this.attrs());
    };

    Dctr.prototype.metaAttrs = function() {
      return {
        create: {
          _index: "dctrs",
          _type: "dctr",
          _id: this.npi()
        }
      };
    };

    Dctr.prototype.attrs = function() {
      return {
        npi: this.npi()
      };
    };

    Dctr.prototype.npi = function() {
      return this.csv[0];
    };

    return Dctr;

  })();

  module.exports = Dctr;

}).call(this);
