// Generated by CoffeeScript 1.7.1
(function() {
  var Taxonomies, taxonomies;

  taxonomies = require('./../data/taxonomies.json');

  Taxonomies = (function() {
    function Taxonomies(_taxonomies) {
      this._taxonomies = _taxonomies;
    }

    Taxonomies.prototype.transform = function(raw_taxonomy) {
      this.taxonomy = this.findTaxonomy(raw_taxonomy.taxonomy_code);
      raw_taxonomy.type = this.taxonomy["type"];
      raw_taxonomy.classification = this.taxonomy["classification"];
      raw_taxonomy.specialization = this.taxonomy["specialization"];
      return raw_taxonomy;
    };

    Taxonomies.prototype.findTaxonomy = function(code) {
      return this._taxonomies[code] || {};
    };

    return Taxonomies;

  })();

  module.exports = new Taxonomies(taxonomies);

}).call(this);
