// Generated by CoffeeScript 1.7.1
(function() {
  var Dctr, TransformDctrs, csv;

  csv = require("csv");

  Dctr = require("dctr");

  TransformDctrs = (function() {
    function TransformDctrs(_in, out) {
      this["in"] = _in;
      this.out = out;
    }

    TransformDctrs.prototype.transform = function() {
      return csv().from.stream(this["in"]).to.stream(this.out).transform(function(row, index, callback) {
        return process.nextTick(function() {
          var dctr;
          dctr = new Dctr(row);
          return callback(null, "" + (dctr.meta()) + "\n" + (dctr.json()) + "\n");
        });
      });
    };

    return TransformDctrs;

  })();

  module.exports = TransformDctrs;

}).call(this);
